# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.select = QtWidgets.QPushButton(self.centralwidget)
        self.select.setGeometry(QtCore.QRect(330, 110, 75, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.select.setFont(font)
        self.select.setObjectName("select")
        self.photo1 = QtWidgets.QLabel(self.centralwidget)
        self.photo1.setGeometry(QtCore.QRect(10, 260, 380, 310))
        self.photo1.setText("")
        self.photo1.setObjectName("photo1")
        self.photo2 = QtWidgets.QLabel(self.centralwidget)
        self.photo2.setGeometry(QtCore.QRect(400, 260, 380, 310))
        self.photo2.setText("")
        self.photo2.setObjectName("photo2")
        self.result = QtWidgets.QLabel(self.centralwidget)
        self.result.setGeometry(QtCore.QRect(30, 150, 391, 91))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.result.setFont(font)
        self.result.setText("")
        self.result.setObjectName("result")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(40, 40, 141, 21))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.display_dir = QtWidgets.QLabel(self.centralwidget)
        self.display_dir.setGeometry(QtCore.QRect(180, 40, 301, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.display_dir.setFont(font)
        self.display_dir.setText("")
        self.display_dir.setObjectName("display_dir")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(40, 110, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.inputID = QtWidgets.QLineEdit(self.centralwidget)
        self.inputID.setGeometry(QtCore.QRect(120, 110, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.inputID.setFont(font)
        self.inputID.setInputMask("")
        self.inputID.setFrame(True)
        self.inputID.setObjectName("inputID")
        self.select_dir = QtWidgets.QPushButton(self.centralwidget)
        self.select_dir.setGeometry(QtCore.QRect(620, 30, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.select_dir.setFont(font)
        self.select_dir.setObjectName("select_dir")
        self.correct = QtWidgets.QPushButton(self.centralwidget)
        self.correct.setGeometry(QtCore.QRect(620, 70, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.correct.setFont(font)
        self.correct.setObjectName("correct")
        self.remind = QtWidgets.QLabel(self.centralwidget)
        self.remind.setGeometry(QtCore.QRect(180, 70, 261, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.remind.setFont(font)
        self.remind.setText("")
        self.remind.setObjectName("remind")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        self.menufile = QtWidgets.QMenu(self.menubar)
        self.menufile.setObjectName("menufile")
        self.menu = QtWidgets.QMenu(self.menufile)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_2 = QtWidgets.QAction(MainWindow)
        self.action_2.setObjectName("action_2")
        self.action_3 = QtWidgets.QAction(MainWindow)
        self.action_3.setObjectName("action_3")
        self.action_4 = QtWidgets.QAction(MainWindow)
        self.action_4.setObjectName("action_4")
        self.action_5 = QtWidgets.QAction(MainWindow)
        self.action_5.setObjectName("action_5")
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.menu.addAction(self.action_3)
        self.menufile.addAction(self.menu.menuAction())
        self.menufile.addAction(self.action)
        self.menu_2.addAction(self.action_4)
        self.menu_2.addAction(self.action_5)
        self.menubar.addAction(self.menufile.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.select.setText(_translate("MainWindow", "查询"))
        self.label_4.setText(_translate("MainWindow", "试卷文件夹目录"))
        self.label_5.setText(_translate("MainWindow", "输入学号"))
        self.inputID.setPlaceholderText(_translate("MainWindow", "输入要查询的学生学号"))
        self.select_dir.setText(_translate("MainWindow", "选择文件夹"))
        self.correct.setText(_translate("MainWindow", "开始阅卷"))
        self.menufile.setTitle(_translate("MainWindow", "文件"))
        self.menu.setTitle(_translate("MainWindow", "打开"))
        self.menu_2.setTitle(_translate("MainWindow", "菜单"))
        self.action_2.setText(_translate("MainWindow", "试卷图片"))
        self.action_3.setText(_translate("MainWindow", "文件夹"))
        self.action_4.setText(_translate("MainWindow", "开始批卷"))
        self.action_5.setText(_translate("MainWindow", "查询结果"))
        self.action.setText(_translate("MainWindow", "退出"))
        self.setWindowTitle(_translate("MainWindow", "自动阅卷系统"))
